"""empty message

Revision ID: c0cb44ff6aaf
Revises: 4be1e8622f65
Create Date: 2023-06-25 09:29:38.300470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0cb44ff6aaf'
down_revision = '4be1e8622f65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', sa.String(length=100), nullable=False))
        batch_op.drop_column('nameandsur')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nameandsur', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.drop_column('full_name')

    # ### end Alembic commands ###
